export const GET_LISTS_REQUEST = 'GET_LISTS_REQUEST'
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS'
export const GET_LISTS_FAILED = 'GET_LISTS_FAILED'

export const ADD_LIST_REQUEST = 'ADD_LIST_REQUEST'
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS'
export const ADD_LIST_FAILED = 'ADD_LIST_FAILED'

export const EDIT_LIST_REQUEST = 'EDIT_LIST_REQUEST'
export const EDIT_LIST_SUCCESS = 'EDIT_LIST_SUCCESS'
export const EDIT_LIST_FAILED = 'EDIT_LIST_FAILED'

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST'
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS'
export const DELETE_LIST_FAILED = 'DELETE_LIST_FAILED'

export const ADD_LIST_ITEM_REQUEST = 'ADD_LIST_ITEM_REQUEST'
export const ADD_LIST_ITEM_SUCCESS = 'ADD_LIST_ITEM_SUCCESS'
export const ADD_LIST_ITEM_FAILED = 'ADD_LIST_ITEM_FAILED'

export const EDIT_LIST_ITEM_REQUEST = 'EDIT_LIST_ITEM_REQUEST'
export const EDIT_LIST_ITEM_SUCCESS = 'EDIT_LIST_ITEM_SUCCESS'
export const EDIT_LIST_ITEM_FAILED = 'EDIT_LIST_ITEM_FAILED'

export const DELETE_LIST_ITEM_REQUEST = 'DELETE_LIST_ITEM_REQUEST'
export const DELETE_LIST_ITEM_SUCCESS = 'DELETE_LIST_ITEM_SUCCESS'
export const DELETE_LIST_ITEM_FAILED = 'DELETE_LIST_ITEM_FAILED'
